/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-12-15 16:35:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Time_0020Table;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import jspbook.pr36.LectureBean;

public final class practice37_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1701954231870L));
    _jspx_dependants.put("jar:file:/C:/Users/qustj/OneDrive/바탕%20화면/week5/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/practice/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("jspbook.pr36.LectureBean");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 request.setCharacterEncoding("UTF-8"); 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>시간표 작성</title>\r\n");
      out.write("<style>\r\n");
      out.write("	    table{\r\n");
      out.write("	        border-collapse: collapse;\r\n");
      out.write("	    }\r\n");
      out.write("	\r\n");
      out.write("	    table, th, td{\r\n");
      out.write("	        border: 1px solid black;\r\n");
      out.write("	    }\r\n");
      out.write("	    caption {\r\n");
      out.write("	        font-size: 20px;\r\n");
      out.write("	        font-weight: bold;\r\n");
      out.write("	\r\n");
      out.write("	    }\r\n");
      out.write("	    th, td {\r\n");
      out.write("	        width: 90px;\r\n");
      out.write("	        height : 50px;\r\n");
      out.write("	    }\r\n");
      out.write("	    th{\r\n");
      out.write("	        font-size: 20px;\r\n");
      out.write("	    }\r\n");
      out.write("	    td{\r\n");
      out.write("	        font-size: 13px;\r\n");
      out.write("	        text-align: center;\r\n");
      out.write("	    }\r\n");
      out.write("	\r\n");
      out.write("	    td.yellow {\r\n");
      out.write("	        background-color: #f5e198;\r\n");
      out.write("	    }\r\n");
      out.write("	    td.blue {\r\n");
      out.write("	        background-color: #bcccfa;\r\n");
      out.write("	    }\r\n");
      out.write("	    td.gray {\r\n");
      out.write("	        background-color: #bdbdbd;\r\n");
      out.write("	    }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      jspbook.pr36.LectureBean info = null;
      info = (jspbook.pr36.LectureBean) _jspx_page_context.getAttribute("info", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (info == null){
        info = new jspbook.pr36.LectureBean();
        _jspx_page_context.setAttribute("info", info, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      out.write('	');
      jspbook.pr36.LectureManager manage = null;
      synchronized (session) {
        manage = (jspbook.pr36.LectureManager) _jspx_page_context.getAttribute("manage", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (manage == null){
          manage = new jspbook.pr36.LectureManager();
          _jspx_page_context.setAttribute("manage", manage, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("info"), request);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("manage"), request);
      out.write('\r');
      out.write('\n');

	if (info.getTitle() != -1){
		manage.add(info);
	}
	manage.buildMatrix();

      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<form action=\"practice37.jsp\">\r\n");
      out.write("		과목타입 : <select name=type>\r\n");
      out.write("		<option value=0>전공필수</option>\r\n");
      out.write("		<option value=1>전공선택</option>\r\n");
      out.write("		<option value=2>교양</option>\r\n");
      out.write("		<option value=3>자유선택</option>\r\n");
      out.write("		</select>\r\n");
      out.write("		과목명 : <select name=title>\r\n");
      out.write("		<option value=0>웹프로그래밍</option>\r\n");
      out.write("		<option value=1>운영체제</option>\r\n");
      out.write("		<option value=2>소프트웨어프로그래밍</option>\r\n");
      out.write("		<option value=3>데이터베이스개론</option>\r\n");
      out.write("		<option value=4>자료구조</option>\r\n");
      out.write("		<option value=5>네트워크</option>\r\n");
      out.write("		<option value=6>창의와감성</option>\r\n");
      out.write("		<option value=7>사회봉사</option>\r\n");
      out.write("		</select>\r\n");
      out.write("		요일 : <select name=day>\r\n");
      out.write("		<option value=0>월</option>\r\n");
      out.write("		<option value=1>화</option>\r\n");
      out.write("		<option value=2>수</option>\r\n");
      out.write("		<option value=3>목</option>\r\n");
      out.write("		<option value=4>금</option> \r\n");
      out.write("		</select>\r\n");
      out.write("		시간 : <select name=time>\r\n");
      out.write("		<option value=1>1</option>\r\n");
      out.write("		<option value=2>2</option>\r\n");
      out.write("		<option value=3>3</option>\r\n");
      out.write("		<option value=4>4</option>\r\n");
      out.write("		<option value=5>5</option>\r\n");
      out.write("		<option value=6>6</option>\r\n");
      out.write("		</select>\r\n");
      out.write("		연강여부 : <select name=consecutive>\r\n");
      out.write("		<option value=1>1</option>\r\n");
      out.write("		<option value=2>2</option>\r\n");
      out.write("		<option value=3>3</option>\r\n");
      out.write("		<option value=4>4</option>\r\n");
      out.write("		<option value=5>5</option>\r\n");
      out.write("		<option value=6>6</option>\r\n");
      out.write("		</select>\r\n");
      out.write("		&nbsp;&nbsp;\r\n");
      out.write("		<input type=submit value=\"등록\">\r\n");
      out.write("		<hr>\r\n");
      out.write("	</form>\r\n");
      out.write("	<div align = \"center\">\r\n");
      out.write("    	<h2>강의 시간표</h2>\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th>2학년</th>\r\n");
      out.write("                <th>월</th>\r\n");
      out.write("                <th>화</th>\r\n");
      out.write("                <th>수</th>\r\n");
      out.write("                <th>목</th>\r\n");
      out.write("                <th>금</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("         </table>\r\n");
      out.write("	</div>\r\n");

	ArrayList<LectureBean> list = (ArrayList<LectureBean>)manage.getLectureList();
	String slist = "";
	if (list != null){
		for (int i = 0; i < list.size(); i++){
			slist += list.get(i).toString() + "<br>";
		}
	}

      out.write("\r\n");
      out.write("	<p>\r\n");
      out.write("	<hr>\r\n");
      out.write("	<p>\r\n");
      out.write("	<div align=center>");
      out.print(slist );
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /Time Table/practice37.jsp(118,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("i");
      // /Time Table/practice37.jsp(118,12) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setBegin(1);
      // /Time Table/practice37.jsp(118,12) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setEnd(6);
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("            	");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${manage.getTable(i-1) }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
